# App Name
spring.application.name=gold

# Cấu hình kết nối MySQL
spring.jpa.database=mysql
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/gold?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# Cấu hình Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ghi đè Bean nếu trùng tên
spring.main.allow-bean-definition-overriding=true

# Cấu hình Upload File (Đã sửa lại dung lượng)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# Cấu hình đường dẫn lưu file cứng
app.file.upload-dir=uploads

# Cấu hình JWT (Thời hạn 86400000 ms = 1 ngày)
jwt.secret=mySecretKeyForJWTAuthenticationSpringBoot2026VeryStrong
jwt.expiration=86400000